### ISSUE TITLE
Very specific parse errors in PL/SQL

### ISSUE THREAD

**Issue by phartenfeller** [IslandSQL/IslandSQL#201]
I encountered parsing errors in one of my packages and simplified the code down to this. The error message says extraneous input 'procedure' and 'end' in line 16 and 22.

The root cause seems to be line 3, 11 and 12. Weirdly, if you comment out any of these 3 lines parsing works.

```sql
create or replace PACKAGE BODY "TEST_PKG" is
  g_debug_text   constant varchar2(10) default 'YES';
  g_debug        constant boolean  default case when g_debug_text in ('YES', 'LEVEL6', 'LEVEL9') then true else false end;

  procedure xyz(
    pi_a in varchar2
  ) as
    v_bool boolean := true;
    v_used_app_id number := 0;
  begin
    apex_debug.info(case when v_bool then 'true' else 'false' end);
    apex_debug.info(v_used_app_id);
    
  end xyz;

  procedure abc(
    pi_a in varchar2
  ) as 
  begin
    null;
  end;
end "TEST_PKG";
/
```

**Comment by PhilippSalvisberg** [comment]
Thanks @phartenfeller for reporting this issue. It's a bug in the scope lexer. In the VS Code extension, you can visualise what the scope lexer is hiding:

![image](https://github.com/user-attachments/assets/b56ea834-e4aa-4843-ac97-1fd1a76d07eb)
 
When you disable the scope lexer in VS Code

![image](https://github.com/user-attachments/assets/8eda1aad-6c38-4cd2-8bb9-204ef44a1b8e)

You won't get parse errors anymore. 

We need a working scope lexer. We will fix it.
