### ISSUE TITLE
Parse error when using table alias at unexpected position

### ISSUE THREAD

**Issue by PhilippSalvisberg** [IslandSQL/IslandSQL#74]
Here's an example from @kibeha's Practical Oracle SQL:

```sql
select wh, aisle, pos, qty, run_qty, box#, box_qty
from (
   select
      product_name
    , warehouse as wh
    , aisle
    , position  as pos
    , qty
   from inventory_with_dimsr
   where product_name = 'Der Helle Kumpel'
) iwd
match_recognize (
   order by wh, aisle, pos
   measures
      match_number()   as box#
    , running sum(qty) as run_qty
    , final   sum(qty) as box_qty
   all rows per match
   pattern (
      fits_in_box+
   )
   define
      fits_in_box as sum(qty) <= 72
)
order by wh, aisle, pos;
``` 

For this working SQL statement the following syntax error is reported in the VS Code extension:

![image](https://github.com/IslandSQL/IslandSQL/assets/3883171/4c8337db-bf9f-4ab9-af7f-5d6d6d295796)

The reason for this syntax error is the table alias `iwd`. According to the [SQL Language Reference 23c](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6__I2126863) the table alias `t_alias` has to be placed after the `row_pattern_clause`.

![image](https://github.com/IslandSQL/IslandSQL/assets/3883171/9d8a3382-e699-4276-9e04-c84668631088)

It should not be possible to define a `t_alias` before the `row_pattern_clause` as in the SQL statement before. In fact, the table alias `iwd` cannot be used in `match_recognize` nor in the `order_by_clause`. This is a clear indicator that the documentation is correct.

Since the Oracle Database accepts this syntax (for whatever reason), we should change the grammar to accept this syntax as well, even if it does not make sense.

The "correct" statement would look like this:

```sql
select wh, aisle, pos, qty, run_qty, box#, box_qty
from (
   select
      product_name
    , warehouse as wh
    , aisle
    , position  as pos
    , qty
   from inventory_with_dims
   where product_name = 'Der Helle Kumpel'
)
match_recognize (
   order by wh, aisle, pos
   measures
      match_number()   as box#
    , running sum(qty) as run_qty
    , final   sum(qty) as box_qty
   all rows per match
   pattern (
      fits_in_box+
   )
   define
      fits_in_box as sum(qty) <= 72
) iwd
order by wh, aisle, pos;
```

**Comment by kibeha** [comment]
Woops, I have a bug in my book 😱 😄 (but I can blame Oracle that the database didn't catch my bug 😉).

Are you using my book code as a testing reference? I'm glad it can be useful 👍.

**Comment by PhilippSalvisberg** [comment]
> Woops, I have a bug in my book 😱 😄 (but I can blame Oracle that the database didn't catch my bug 😉).

I would not call it a bug in your book. In the end, the statement works and produces a correct result. However, I agree that the Oracle Database should have thrown an error. Fixing it right now is unrealistic since it would break working code. So, no worries 😉.

> Are you using my book code as a testing reference? I'm glad it can be useful 👍.

While I have tons of parametrized tests (currently around 120K) I still like to run the parser against real code. And the examples in your book are among them. Thank you, Kim.
