### ISSUE TITLE
Parse error when using `with unmatched rows` in match_recognize

### ISSUE THREAD

**Issue by PhilippSalvisberg** [IslandSQL/IslandSQL#75]
Here's another working SQL of @kibeha's Practical Oracle SQL book:

```sql
select wh, aisle, pos, qty, run_qty, box#, box_qty
from (
   select
      product_name
    , warehouse as wh
    , aisle
    , position  as pos
    , qty
   from inventory_with_dims
   where product_name = 'Der Helle Kumpel'
) 
match_recognize (
   order by wh, aisle, pos
   measures
      match_number()   as box#
    , running sum(qty) as run_qty
    , final   sum(qty) as box_qty
   all rows per match with unmatched rows
   pattern (
      fits_in_box+
   )
   define
      fits_in_box as sum(qty) <= 64
) iwd
order by wh, aisle, pos;
```

The example works, but syntax error is reported in the VS Code extension:

![image](https://github.com/IslandSQL/IslandSQL/assets/3883171/6fe255ce-d59a-4539-ac15-a89056dec70a)

It looks like the `with unmatched rows` clause is not documented in the [SQL Language Reference 23c](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6__BABFAJHB)

![image](https://github.com/IslandSQL/IslandSQL/assets/3883171/4b7084d7-01b3-4223-ae57-79f15b6c0878)

However, @KeithLaker documented the following options in [LiveSQL](https://livesql.oracle.com/apex/livesql/file/tutorial_DZO3CVNYA7IYFU1V8H0PWHPYN.html):

- `SHOW EMPTY MATCHES` (the default)
- `OMIT EMPTY MATCHES`
- `WITH UNMATCHED ROWS`

We should extend the grammar to cover these options.

**Comment by kibeha** [comment]
Does look like a doc bug in SQL reference.
It's detailed in the Warehouse guide:
https://docs.oracle.com/en/database/oracle/oracle-database/23/dwhsg/sql-pattern-matching-data-warehouses.html#GUID-D3AD7864-B350-4E58-8794-EB87A1EE3F6D

**Comment by PhilippSalvisberg** [comment]
Thank you @kibeha for pointing me to the Data Warehousing Guide. Yes, the SQL Language Reference should cover the complete syntax. There are similar issues with JSON-related stuff that are not fully documented in the SQL Language Reference, but you can find more information about it in the JSON Developer's Guide. I have a backlog of documentation bugs I'd like to report.
